fix error handling

diff --git a/.github/actions/Run-Workflow/action.yml b/.github/actions/Run-Workflow/action.yml
--- a/.github/actions/Run-Workflow/action.yml
+++ b/.github/actions/Run-Workflow/action.yml
@@ -100,7 +100,7 @@ runs:
         until [ $isFinished -gt 0 ] ; do
           echo "$(date -u +%T) UTC: Waiting 30 seconds to check workflow status ..."
           sleep 30s
-          runData="$(gh run list --repo "${{ inputs.repo }}" --json "${fieldlist}" --workflow ${{ inputs.workflow }} --limit 1 || "gh failed")"
+          runData="$(gh run list --repo "${{ inputs.repo }}" --json "${fieldlist}" --workflow ${{ inputs.workflow }} --limit 1 || echo "gh failed")"
           if [ "${{ inputs.debug }}" = "true" ] ; then
             echo "goal: ${{ inputs.goal }}"
             echo "ref: ${{ inputs.ref }}"
